# Generated by Django 5.1.15 on 2026-05-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Pochta kodi')),
                ('name', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Viloyat')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('is_airport', models.BooleanField(default=False, verbose_name="Aeroport bo'limi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Pochta bo'limi",
                'verbose_name_plural': "Pochta bo'limlari",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Lavozim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postal_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='accounts.postaloffice', verbose_name="Pochta bo'limi")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim profili',
                'verbose_name_plural': 'Xodimlar profillari',
            },
        ),
    ]
