# Generated by Django 5.1.15 on 2026-05-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postaloffice',
            options={'ordering': ['code'], 'verbose_name': 'Pochta/Bojxona posti', 'verbose_name_plural': 'Pochta/Bojxona postlari'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['postal_office__code', 'full_name'], 'verbose_name': 'Xodim profili (Intervyuver)', 'verbose_name_plural': 'Xodimlar profillari (Intervyuverlar)'},
        ),
        migrations.AddField(
            model_name='postaloffice',
            name='post_type',
            field=models.CharField(choices=[('airport', 'Xalqaro aeroport'), ('auto', 'Avto bojxona posti'), ('railway', "Temir yo'l bojxona posti"), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Post turi'),
        ),
        migrations.AddField(
            model_name='postaloffice',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, help_text='4 raqamli, masalan 1735', max_length=10, verbose_name='Hudud kodi'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text="Excel'dan import qilingan asl ism (masalan: Tajibekov Baxtiyar Nietullaevich)", max_length=255, verbose_name="To'liq F.I.SH (Excel'dan)"),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Hudud kodi'),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Post kodi'),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Bo'lim nomi"),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='postal_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='accounts.postaloffice', verbose_name='Asosiy post'),
        ),
    ]
