# Generated by Django 5.1.15 on 2026-05-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_can_enter_surveys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='TOTP secret (base32)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_verified', models.BooleanField(default=False, help_text="True boʻlsa, foydalanuvchi QR'ni skanlab birinchi kodni kiritgan.", verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_totp', to=settings.AUTH_USER_MODEL, verbose_name='Admin foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin 2FA qurilmasi',
                'verbose_name_plural': 'Admin 2FA qurilmalari',
            },
        ),
    ]
