# Generated by Django 5.1.15 on 2026-05-08 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_type', models.CharField(choices=[('inbound', 'Inbound (xorijliklar)'), ('outbound', 'Outbound (chiqish)')], db_index=True, max_length=10, verbose_name="So'rovnoma turi")),
                ('source', models.CharField(choices=[('public', "Turist o'zi to'ldirgan"), ('staff', 'Xodim kiritgan')], db_index=True, default='public', max_length=10, verbose_name='Manba')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Til')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Mamlakat')),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Tashrif maqsadi')),
                ('nights', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tunlar soni')),
                ('total_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Umumiy xarajat')),
                ('spent_currency', models.CharField(blank=True, max_length=10, verbose_name='Valyuta')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Javoblar (JSON)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Yakunlanganmi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('postal_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='accounts.postaloffice', verbose_name="Pochta bo'limi")),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan xodim')),
            ],
            options={
                'verbose_name': "So'rovnoma javobi",
                'verbose_name_plural': "So'rovnoma javoblari",
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['survey_type', '-started_at'], name='surveys_sur_survey__f9ab14_idx'), models.Index(fields=['source', '-started_at'], name='surveys_sur_source_dc9858_idx')],
            },
        ),
    ]
