# Generated by Django 5.1.15 on 2026-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kenglik (latitude)'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS aniqligi (metr)'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='location_granted',
            field=models.BooleanField(default=False, verbose_name='GPS ruxsat berildi'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Uzunlik (longitude)'),
        ),
    ]
